version: '3.4'

services:
  catalogdb:
    image: postgres
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  basketdb:
    image: postgres
    volumes:
      - postgres_basket:/var/lib/postgresql/data
  orderdb:
    image: mcr.microsoft.com/mssql/server

  distributedcache:
    image: redis

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/BasketApi/Dockerfile
  apigateways:
    image: ${DOCKER_REGISTRY-}apigateways
    build:
      context: .
      dockerfile: ApiGateways/ApiGateways/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


